version: '3'

services:
  download:
    build: ./download
    volumes:
      - ${OSM_DIR:-osm}:/data/osm
      - ${ADDR_DIR:-addr}:/data/addresses
      - ${COSMOGONY_DIR:-cosmogony}:/data/cosmogony

  mimir:
    image: navitia/mimirsbrunn
    volumes:
      - ${OSM_DIR:-osm}:/data/osm
      - ${ADDR_DIR:-addr}:/data/addresses
      - ${COSMOGONY_DIR:-cosmogony}:/data/cosmogony
    environment:
      - RUST_LOG=info,hyper=warn,rs_es=warn

  es:
    image: elasticsearch:2
    ports:
      - 9200

  bragi:
    image: navitia/bragi
    environment:
      - BRAGI_ES=http://es:9200
    ports:
      - 4000

  cosmogony:
    image: osmwithoutborders/cosmogony
    volumes:
      - ${OSM_DIR:-osm}:/data/osm
      - ${COSMOGONY_DIR:-cosmogony}:/data/cosmogony

  fafnir:
    image: qwantresearch/fafnir
    environment:
      - RUST_LOG=warn,fafnir=info,mimir=info

volumes:
  osm:
  cosmogony:
  addr:
