# example file to run mimir in docker

es: http://es:9200

osm:
  url: https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf

admin:
  cosmogony:
    output_dir: /data/cosmogony
    langs: "fr,en,de"

street:
  osm_db_file: /data/osm/osm_db.tmp

addresses:
  use_deduplicator: false

  osm:
    url: # https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf

  oa:
    # URL for the zip archive containing all data.
    url: https://data.openaddresses.io/openaddr-collected-europe.zip

    # Patterns of file to import URLs from.
    include:
      - lu/**.csv
      # - at/**.csv
      # - be/**.csv
      # - de/**.csv
      # - dk/**.csv
      # - ee/**.csv
      # - es/**.csv
      # - fi/**.csv
      # - fr/**.csv
      # - gr/**.csv
      # - it/**.csv
      # - lt/**.csv
      # - nl/**.csv
      # - pl/**.csv
      # - pt/**.csv
      # - se/**.csv
      # - si/**.csv
      # - sk/**.csv

geocoder_tester_region: luxembourg
